# Generated by Django 5.0.3 on 2024-04-04 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('studentapi', '0002_alter_studentuser_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='studentapi.studentuser')),
                ('teacher', models.ManyToManyField(related_name='teaches', to='api.teacheruser')),
            ],
        ),
    ]
