# Generated by Django 5.0.3 on 2024-04-04 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('studentapi', '0004_remove_subject_student_remove_subject_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(related_name='teaches', to='studentapi.studentuser'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='api.teacheruser'),
        ),
    ]
