# Generated by Django 5.0.4 on 2024-04-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapi', '0008_alter_result_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='teachers',
        ),
    ]
